module Students
( Student
, name
, surname
, sex
, day
, month
, year
, group
, iq
, students
, french
, discrete_mathematics
, programming 
, student_pupkin
) where

data Student = St {name, surname :: String, sex :: Char, day, month, year :: Int, group :: Int, iq :: Int} deriving (Show, Read)

instance Eq Student where
  (==) x  y = surname x == surname y

instance Ord Student where
  (>) x  y = surname x > surname y
  (<) x  y = surname x < surname y

student_pupkin = St {name="Василий", surname="Пупкин", sex='м', day=19, month=2, year=1991, group=313, iq=120};

students = [
  St {name="Максим", surname="Чуркин", sex='m', day=13, month=12, year=1991, group=331, iq=100},
  St {name="Вера", surname="Аминова", sex='f', day=1, month=6, year=1991, group=331, iq=115},
  St {name="Елизавета", surname="Анохина", sex='f', day=27, month=2, year=1992, group=332, iq=105},
  St {name="Дарья", surname="Грекова", sex='f', day=18, month=3, year=1992, group=333, iq=106},
  St {name="Иван", surname="Демкович", sex='m', day=3, month=1, year=1993, group=331, iq=107},
  St {name="Денис", surname="Дубленых", sex='m', day=6, month=4, year=1991, group=334, iq=106},
  St {name="Алексей", surname="Королев", sex='m', day=24, month=5, year=1993, group=333, iq=114},
  St {name="Вячеслав", surname="Шапрынский", sex='m', day=28, month=11, year=1992, group=334, iq=103},
  St {name="Владислав", surname="Исенбаев", sex='m', day=11, month=10, year=1991, group=331, iq=103},
  St {name="Дмитрий", surname="Зонин", sex='m', day=10, month=4, year=1991, group=332, iq=108},
  St {name="Дмитрий", surname="Карпов", sex='m', day=9, month=8, year=1991, group=331, iq=108},
  St {name="Александр", surname="Голубев", sex='m', day=19, month=9, year=1992, group=332, iq=106},
  St {name="Вадим", surname="Шакуро", sex='m', day=5, month=1, year=1992, group=333, iq=108},
  St {name="Сергей", surname="Ларюшкин", sex='m', day=9, month=3, year=1993, group=333, iq=107},
  St {name="Александр", surname="Сухман", sex='m', day=20, month=2, year=1993, group=331, iq=115},
  St {name="Кирилл", surname="Корнюхин", sex='m', day=30, month=12, year=1992, group=332, iq=106},
  St {name="Марина", surname="Масленникова", sex='f', day=29, month=3, year=1990, group=332, iq=114},
  St {name="Антон", surname="Путрик", sex='m', day=2, month=11, year=1991, group=331, iq=107},
  St {name="Максим", surname="Путрик", sex='m', day=16, month=10, year=1991, group=332, iq=107},
  St {name="Александр", surname="Чегодаев", sex='m', day=12, month=9, year=1993, group=332, iq=105},
  St {name="Виктор", surname="Самунь", sex='m', day=19, month=7, year=1992, group=331, iq=108},
  St {name="Дмитрий", surname="Королев", sex='m', day=22, month=6, year=1991, group=333, iq=106},
  St {name="Павел", surname="Скрипниченко", sex='m', day=11, month=5, year=1991, group=331, iq=115},
  St {name="Александр", surname="Топоров", sex='m', day=4, month=11, year=1991, group=334, iq=102},
  St {name="Елена", surname="Шалашугина", sex='f', day=5, month=12, year=1992, group=331, iq=105},
  St {name="Денис", surname="Ядаринкин", sex='m', day=17, month=8, year=1992, group=331, iq=103},
  St {name="Даниил", surname="Айзенштейн", sex='m', day=15, month=5, year=1993, group=331, iq=105},
  St {name="Вера", surname="Аминова", sex='f', day=26, month=4, year=1993, group=332, iq=106},
  St {name="Ксения", surname="Афоненко", sex='f', day=18, month=3, year=1993, group=332, iq=103},
  St {name="Илья", surname="Дегтярев", sex='m', day=28, month=2, year=1992, group=333, iq=106},
  St {name="Дмитрий", surname="Зонин", sex='m', day=22, month=1, year=1992, group=331, iq=106},
  St {name="Мария", surname="Колмогорова", sex='f', day=21, month=9, year=1991, group=333, iq=103},
  St {name="Виктор", surname="Самунь", sex='m', day=7, month=7, year=1992, group=331, iq=109},
  St {name="Олег", surname="Михайлов", sex='m', day=6, month=11, year=1992, group=331, iq=107},
  St {name="Григорий", surname="Семенов", sex='m', day=14, month=10, year=1989, group=334, iq=102},
  St {name="Иван", surname="Кадочников", sex='m', day=22, month=7, year=1993, group=334, iq=103},
  St {name="Алексей", surname="Королев", sex='m', day=15, month=6, year=1991, group=331, iq=102},
  St {name="Алексей", surname="Кутырев", sex='m', day=1, month=5, year=1991, group=331, iq=111},
  St {name="Елена", surname="Лысенко", sex='f', day=28, month=1, year=1990, group=333, iq=107},
  St {name="Антон", surname="Путрик", sex='m', day=23, month=11, year=1992, group=333, iq=107},
  St {name="Илья", surname="Отрадников", sex='m', day=15, month=3, year=1992, group=331, iq=115},
  St {name="Анна", surname="Уставщикова", sex='f', day=10, month=2, year=1991, group=334, iq=100},
  St {name="Борис", surname="Сафронов", sex='m', day=20, month=8, year=1993, group=334, iq=105},
  St {name="Надежда", surname="Скачкова", sex='f', day=1, month=12, year=1991, group=331, iq=111},
  St {name="Владимир", surname="Теличкин", sex='m', day=8, month=7, year=1991, group=331, iq=114},
  St {name="Иван", surname="Турмышев", sex='m', day=7, month=5, year=1992, group=332, iq=107},
  St {name="Евгений", surname="Кузнецов", sex='m', day=4, month=11, year=1992, group=331, iq=108},
  St {name="Сергей", surname="Зайков", sex='m', day=3, month=8, year=1991, group=331, iq=108},
  St {name="Юлия", surname="Буркова", sex='f', day=13, month=3, year=1991, group=331, iq=109},
  St {name="Юрий", surname="Старовойтов", sex='m', day=12, month=4, year=1993, group=334, iq=102},
  St {name="Яков", surname="Мозгоев", sex='m', day=10, month=9, year=1991, group=332, iq=107},
  St {name="Елена", surname="Михайлова", sex='f', day=27, month=12, year=1993, group=334, iq=111},
  St {name="Егор", surname="Игнатьев", sex='m', day=26, month=9, year=1992, group=333, iq=107},
  St {name="Сергей", surname="Торопкин", sex='m', day=21, month=4, year=1991, group=331, iq=101},
  St {name="Татьяна", surname="Елисеева", sex='f', day=25, month=6, year=1991, group=333, iq=100},
  St {name="Адель", surname="Аухатова", sex='f', day=12, month=3, year=1991, group=332, iq=105},
  St {name="Алексей", surname="Ефремов", sex='m', day=19, month=2, year=1993, group=334, iq=105},
  St {name="Диана", surname="Таратухина", sex='f', day=17, month=1, year=1992, group=334, iq=102},
  St {name="Ростислав", surname="Девятов", sex='m', day=5, month=8, year=1992, group=334, iq=108},
  St {name="Антон", surname="Васильев", sex='m', day=2, month=5, year=1991, group=332, iq=112},
  St {name="Антон", surname="Махлин", sex='m', day=8, month=4, year=1990, group=332, iq=109},
  St {name="Елена", surname="Третьяк", sex='f', day=16, month=3, year=1993, group=333, iq=105},
  St {name="Игорь", surname="Гуламов", sex='m', day=25, month=6, year=1991, group=333, iq=105},
  St {name="Борис", surname="Перельман", sex='m', day=13, month=3, year=1992, group=332, iq=115},
  St {name="Илья", surname="Корнаков", sex='m', day=22, month=12, year=1992, group=333, iq=101},
  St {name="Владимир", surname="Батаев", sex='m', day=10, month=10, year=1991, group=334, iq=102},
  St {name="Арсений", surname="Климовский", sex='m', day=4, month=5, year=1991, group=331, iq=102},
  St {name="Федор", surname="Пахомов", sex='m', day=17, month=3, year=1993, group=334, iq=107},
  St {name="Виктор", surname="Алюшин", sex='m', day=10, month=12, year=1993, group=334, iq=101},
  St {name="Игорь", surname="Махлин", sex='m', day=28, month=1, year=1992, group=332, iq=108},
  St {name="Иван", surname="Козлов", sex='m', day=21, month=8, year=1991, group=332, iq=111},
  St {name="Вадим", surname="Авдеев", sex='m', day=11, month=3, year=1992, group=333, iq=111},
  St {name="Антон", surname="Фонарев", sex='m', day=3, month=9, year=1991, group=332, iq=107},
  St {name="Андрей", surname="Колосов", sex='m', day=1, month=7, year=1991, group=332, iq=107},
  St {name="Марина", surname="Степанова", sex='f', day=9, month=11, year=1992, group=334, iq=104},
  St {name="Матвей", surname="Корнилов", sex='m', day=7, month=10, year=1993, group=334, iq=105},
  St {name="Яков", surname="Длугач", sex='m', day=5, month=5, year=1991, group=333, iq=109},
  St {name="Игорь", surname="Туркин", sex='m', day=4, month=5, year=1991, group=333, iq=109},
  St {name="Олег", surname="Самойленко", sex='m', day=1, month=8, year=1992, group=332, iq=107},
  St {name="Екатерина", surname="Самбукова", sex='f', day=15, month=3, year=1993, group=334, iq=104},
  St {name="Дмитрий", surname="Алексеев", sex='m', day=25, month=2, year=1992, group=334, iq=104},
  St {name="Павел", surname="Ющенко", sex='m', day=21, month=10, year=1990, group=334, iq=108},
  St {name="Иван", surname="Дудинов", sex='m', day=22, month=12, year=1991, group=331, iq=108},
  St {name="Виктор", surname="Чернышов", sex='m', day=16, month=4, year=1991, group=331, iq=99},
  St {name="Антон", surname="Лупанов", sex='m', day=11, month=12, year=1993, group=333, iq=108},
  St {name="Иван", surname="Пузыревский", sex='m', day=6, month=1, year=1991, group=333, iq=99},
  St {name="Александр", surname="Петров", sex='m', day=20, month=1, year=1992, group=332, iq=107},
  St {name="Леонид", surname="Андриевский", sex='m', day=17, month=7, year=1990, group=334, iq=107},
  St {name="Александр", surname="Рощупкин", sex='m', day=1, month=3, year=1991, group=333, iq=98},
  St {name="Александр", surname="Корчагин", sex='m', day=15, month=7, year=1991, group=334, iq=112},
  St {name="Кирилл", surname="Жалнин", sex='m', day=10, month=8, year=1992, group=332, iq=104},
  St {name="Дмитрий", surname="Горбик", sex='m', day=13, month=6, year=1991, group=332, iq=104},
  St {name="Антон", surname="Бобков", sex='m', day=27, month=2, year=1991, group=333, iq=104},
  St {name="Константин", surname="Новиков", sex='m', day=22, month=10, year=1993, group=332, iq=101},
  St {name="Владимир", surname="Ткачев", sex='m', day=21, month=1, year=1992, group=334, iq=94},
  St {name="Иван", surname="Кондрашов", sex='m', day=6, month=5, year=1994, group=331, iq=104},
  St {name="Данила", surname="Потапов", sex='m', day=23, month=6, year=1991, group=332, iq=104},
  St {name="Борис", surname="Агафонцев", sex='m', day=13, month=4, year=1993, group=334, iq=135},
  St {name="Алексей", surname="Давыдов", sex='m', day=7, month=7, year=1993, group=333, iq=103},
  St {name="Денис", surname="Лисов", sex='m', day=4, month=12, year=1990, group=333, iq=108},
  St {name="Иван", surname="Богатый", sex='m', day=14, month=4, year=1991, group=333, iq=107},
  St {name="Мария", surname="Фелицина", sex='f', day=18, month=2, year=1990, group=333, iq=104},
  St {name="Андрей", surname="Викулов", sex='m', day=2, month=2, year=1993, group=332, iq=107},
  St {name="Алексей", surname="Крицин", sex='m', day=22, month=12, year=1991, group=332, iq=107},
  St {name="Артем", surname="Кухаренко", sex='m', day=26, month=7, year=1990, group=332, iq=103},
  St {name="Сергей", surname="Аноховский", sex='m', day=30, month=4, year=1993, group=331, iq=103},
  St {name="Александр", surname="Захаров", sex='m', day=29, month=12, year=1991, group=332, iq=103},
  St {name="Андрей", surname="Котов", sex='m', day=28, month=10, year=1991, group=333, iq=111},
  St {name="Кирилл", surname="Знаменский", sex='m', day=30, month=9, year=1993, group=334, iq=103},
  St {name="Владимир", surname="Лесниченко", sex='m', day=31, month=8, year=1993, group=334, iq=103},
  St {name="Илья", surname="Смирнов", sex='m', day=31, month=7, year=1991, group=331, iq=108},
  St {name="Александр", surname="Колесников", sex='m', day=31, month=3, year=1991, group=334, iq=101},
  St {name="Николай", surname="Печенкин", sex='m', day=13, month=11, year=1991, group=333, iq=115},
  St {name="Игнат", surname="Колесниченко", sex='m', day=29, month=7, year=1990, group=332, iq=101},
  St {name="Алена", surname="Шевцова", sex='f', day=30, month=2, year=1993, group=334, iq=106},
  St {name="Федор", surname="Волков", sex='m', day=30, month=3, year=1993, group=333, iq=107},
  St {name="Константин", surname="Яблочкин", sex='m', day=9, month=1, year=1990, group=334, iq=109},
  St {name="Алексей", surname="Окунев", sex='m', day=31, month=12, year=1991, group=334, iq=107},
  St {name="Татьяна", surname="Поиленкова", sex='f', day=31, month=7, year=1991, group=334, iq=101},
  St {name="Ольга", surname="Пакуляк", sex='f', day=31, month=3, year=1991, group=333, iq=108},
  St {name="Элина", surname="Имашева", sex='f', day=31, month=5, year=1993, group=333, iq=108},
  St {name="Алексей", surname="Гронский", sex='m', day=30, month=7, year=1989, group=332, iq=109},
  St {name="Мария", surname="Гребенкина", sex='f', day=31, month=12, year=1991, group=332, iq=106}
  ] :: [Student]

french = [("Максим", "Чуркин"), ("Вера", "Аминова"), ("Дарья", "Грекова"),
              ("Иван", "Демкович"), ("Денис", "Дубленых"), ("Алексей", "Королев"),
              ("Дмитрий", "Зонин"), ("Дмитрий", "Карпов"), ("Вадим", "Шакуро"),
              ("Кирилл", "Корнюхин"), ("Александр", "Чегодаев"), ("Павел", "Скрипниченко"),
              ("Денис", "Ядаринкин"), ("Вера", "Аминова"), ("Ксения", "Афоненко"),
              ("Мария", "Колмогорова"), ("Олег", "Михайлов"), ("Иван", "Кадочников"),
              ("Елена", "Лысенко"), ("Антон", "Путрик"), ("Илья", "Отрадников"),
              ("Анна", "Уставщикова"), ("Сергей", "Зайков"), ("Юлия", "Буркова"),
              ("Елена", "Михайлова"), ("Адель", "Аухатова"), ("Диана", "Таратухина"),
              ("Ростислав", "Девятов"), ("Антон", "Васильев"), ("Елена", "Третьяк"),
              ("Владимир", "Батаев"), ("Федор", "Пахомов"), ("Игорь", "Махлин"),
              ("Иван", "Козлов"), ("Антон", "Фонарев"), ("Яков", "Длугач"),
              ("Игорь", "Туркин"), ("Дмитрий", "Алексеев"), ("Павел", "Ющенко"),
              ("Иван", "Дудинов"), ("Антон", "Лупанов"), ("Иван", "Пузыревский"),
              ("Леонид", "Андриевский"), ("Александр", "Корчагин"), ("Кирилл", "Жалнин"),
              ("Антон", "Бобков"), ("Владимир", "Ткачев"), ("Данила", "Потапов"),
              ("Денис", "Лисов"), ("Иван", "Богатый"), ("Алексей", "Крицин"),
              ("Андрей", "Котов"), ("Кирилл", "Знаменский"), ("Владимир", "Лесниченко"),
              ("Илья", "Смирнов"), ("Александр", "Колесников"), ("Николай", "Печенкин"),
              ("Алена", "Шевцова"), ("Константин", "Яблочкин"), ("Татьяна", "Поиленкова"),
              ("Мария", "Гребенкина")] :: [(String, String)]
              
discrete_mathematics = [("Елизавета", "Анохина"), ("Денис", "Дубленых"), ("Алексей", "Королев"),
                            ("Вячеслав", "Шапрынский"), ("Дмитрий", "Карпов"), ("Сергей", "Ларюшкин"),
                            ("Александр", "Топоров"), ("Даниил", "Айзенштейн"), ("Вера", "Аминова"),
                            ("Ксения", "Афоненко"), ("Дмитрий", "Зонин"), ("Мария", "Колмогорова"),
                            ("Алексей", "Королев"), ("Алексей", "Кутырев"), ("Илья", "Отрадников"),
                            ("Анна", "Уставщикова"), ("Надежда", "Скачкова"), ("Владимир", "Теличкин"),
                            ("Иван", "Турмышев"), ("Евгений", "Кузнецов"), ("Сергей", "Зайков"),
                            ("Юлия", "Буркова"), ("Юрий", "Старовойтов"), ("Яков", "Мозгоев"),
                            ("Елена", "Михайлова"), ("Сергей", "Торопкин"), ("Игорь", "Гуламов"),
                            ("Владимир", "Батаев"), ("Игорь", "Махлин"), ("Иван", "Козлов"),
                            ("Андрей", "Колосов"), ("Марина", "Степанова"), ("Матвей", "Корнилов"),
                            ("Яков", "Длугач"), ("Игорь", "Туркин"), ("Олег", "Самойленко"),
                            ("Виктор", "Чернышов"), ("Антон", "Лупанов"), ("Александр", "Рощупкин"),
                            ("Александр", "Корчагин"), ("Кирилл", "Жалнин"), ("Антон", "Бобков"),
                            ("Константин", "Новиков"), ("Иван", "Кондрашов"), ("Данила", "Потапов"),
                            ("Денис", "Лисов"), ("Мария", "Фелицина"), ("Андрей", "Викулов"),
                            ("Артем", "Кухаренко"), ("Сергей", "Аноховский"), ("Александр", "Захаров"),
                            ("Андрей", "Котов"), ("Владимир", "Лесниченко"), ("Илья", "Смирнов"),
                            ("Александр", "Колесников"), ("Николай", "Печенкин"), ("Алена", "Шевцова"),
                            ("Татьяна", "Поиленкова"), ("Ольга", "Пакуляк"), ("Элина", "Имашева"),
                            ("Алексей", "Гронский"), ("Мария", "Гребенкина")] :: [(String, String)]

programming = [("Дарья", "Грекова"), ("Иван", "Демкович"), ("Денис", "Дубленых"),
                   ("Алексей", "Королев"), ("Владислав", "Исенбаев"), ("Дмитрий", "Зонин"),
                   ("Александр", "Голубев"), ("Вадим", "Шакуро"), ("Кирилл", "Корнюхин"),
                   ("Антон", "Путрик"), ("Максим", "Путрик"), ("Александр", "Чегодаев"),
                   ("Вера", "Аминова"), ("Ксения", "Афоненко"), ("Мария", "Колмогорова"),
                   ("Виктор", "Самунь"), ("Олег", "Михайлов"), ("Алексей", "Королев"),
                   ("Илья", "Отрадников"), ("Анна", "Уставщикова"), ("Иван", "Турмышев"),
                   ("Евгений", "Кузнецов"), ("Юлия", "Буркова"), ("Яков", "Мозгоев"),
                   ("Егор", "Игнатьев"), ("Татьяна", "Елисеева"), ("Адель", "Аухатова"),
                   ("Ростислав", "Девятов"), ("Антон", "Васильев"), ("Елена", "Третьяк"),
                   ("Федор", "Пахомов"), ("Виктор", "Алюшин"), ("Иван", "Козлов"),
                   ("Вадим", "Авдеев"), ("Антон", "Фонарев"), ("Екатерина", "Самбукова"),
                   ("Дмитрий", "Алексеев"), ("Виктор", "Чернышов"), ("Иван", "Пузыревский"),
                   ("Александр", "Петров"), ("Александр", "Рощупкин"), ("Александр", "Корчагин"),
                   ("Антон", "Бобков"), ("Константин", "Новиков"), ("Владимир", "Ткачев"),
                   ("Иван", "Кондрашов"), ("Данила", "Потапов"), ("Алексей", "Давыдов"),
                   ("Денис", "Лисов"), ("Мария", "Фелицина"), ("Андрей", "Викулов"),
                   ("Алексей", "Крицин"), ("Артем", "Кухаренко"), ("Александр", "Захаров"),
                   ("Илья", "Смирнов"), ("Игнат", "Колесниченко"), ("Татьяна", "Поиленкова"),
                   ("Ольга", "Пакуляк"), ("Алексей", "Гронский"), ("Мария", "Гребенкина")] :: [(String, String)]
